### PR TITLE
Log actual start / stop times

### PR DESCRIPTION
**Pull request by mbucc**
Hi,

This donow is quite useful, thank you.  This patch creates a log of task start/stop times.

I did this because I want to track:
- how many times do I switch between tasks on a day
- on average, how many I tasks do I work on in a day

What do you think?

Thanks,

Mark

### CODE REVIEW

**Comment by clobrano** [comment]
Hi,

I like this suggestion, the log could also be used to extract other statistics. 
However I would prefer to avoid forcing users to have such a log file. In my opinion we can leave the variable commented out, explain its meaning and put another check in `elog` function. Something like the following

```
# Uncomment the following to enable 'donow' statistic logging
#EVIDENCE_LOG=$TODO_DIR/evidence.log

elog()
{
    if [ !-z ${EVIDENCE_LOG} ] && [ ! -f ${EVIDENCE_LOG} ] ; then
        touch ${EVIDENCE_LOG}
    fi
    echo $(date "+%F %T") "$1" >> ${EVIDENCE_LOG}
}
```

What do you think?

Carlo

**Comment by clobrano** [comment]
I was missing something

```
# Uncomment the following to enable 'donow' statistic logging
#EVIDENCE_LOG=$TODO_DIR/evidence.log

elog()
{
    if [ !-z ${EVIDENCE_LOG} ] && [ ! -f ${EVIDENCE_LOG} ] ; then
        touch ${EVIDENCE_LOG}
    fi

    if [ -f ${EVIDENCE_LOG ]; then
        echo $(date "+%F %T") "$1" >> ${EVIDENCE_LOG}
    fi
}
```

**Comment by mbucc** [comment]
Yes, I agree ... I will update request.

**Comment by clobrano** [comment]
If you prefer, I can merge this and change it later. 

Let me know

**Pull request merged**
